language: node_js
node_js:
  - "0.10"
env:
  global:
    - secure: "A1ATdfV5E4K8aw2miX9Pm6t71sHYib6fW1SKnHR3jFL0DyWFEMm3cY1uzs0J+Fn2slzuA9BG5MIG+bOkngGsWEEmN8VJNnkdzAWUSCrGdPWE+vUeBsUCv5kT8fkHHG1xXUvMVpnd1twzw6P0A9qcFCcId01sP9022vaVu0MLaMU="
    - secure: "U9XkopIf2gO0mT8ilIv5lQuMSE4J2c0o1HGB//z+XikNQzKJ8KTsMJSSi9BFyG/1AoQtX+oiePNKFkk2d9ONhMkQ+m+Cf50WE4iVxJtOuSjr1v2HouRpC+bWLnYRF4k8DFpH9M6J71p224I2Qk+DgGhi31RC5iLjQTX2pMAylsw="
install:
  - npm install
  - $(npm bin)/bower --version
  - $(npm bin)/bower install
script:
  - npm start
  - $(npm bin)/grunt tentacles
