#!/bin/sh

which ./bbn >/dev/null 2>&1 || { echo >&2 "bbn is required but it's not installed. Aborting."; exit 1; }

script_dir=$(cd "$(dirname "${0}")" >/dev/null 2>&1 && pwd)
root_dir=$(cd "$(dirname "${script_dir}")" >/dev/null 2>&1 && pwd)
data_dir="${root_dir}/data"
dist_dir="${root_dir}/dist"

./bbn build --data-dir "${data_dir}" --out-dir "${dist_dir}"
