#!/usr/bin/env node

const { build } = require('@bouzuya/mr-jums');

build({
  dstDir: 'dist',
  imageBaseUrl: 'https://blog.bouzuya.net/images',
  incremental: true,
  jsonBaseUrl: 'file:./dist'
});
