#!/bin/bash

if [ "${TRAVIS_BRANCH}" != 'master' ]; then exit 0; fi
if [ "${TRAVIS_REPO_SLUG}" != 'bouzuya/blog.bouzuya.net' ]; then exit 0; fi
echo 'deploy'
pyenv global 3.6
pip3 install --quiet --upgrade --user awscli
echo 'aws --version'
aws --version
aws s3 sync --size-only dist s3://blog.bouzuya.net/
